# Generated by Django 4.0.2 on 2022-02-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_board_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
