# Generated by Django 4.0.2 on 2022-02-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_board_writer_board_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='writer',
        ),
    ]
